name = "ActiveInference"
uuid = "688b0e7a-0122-4325-8669-5ff08899a59e"
version = "0.2.0"
authors = ["John Boik", "Jonathan Ehrenreich Laursen", "Samuel William Nehrer", "Peter Thestrup Waade"]

[weakdeps]
ActionModels = "320cf53b-cc3b-4b34-9a10-0ecb113566a3"

[extensions]
ActionModelsExt = "ActionModels"

[compat]
julia = "1.10"
ActionModels = "0.7"
